### ISSUE TITLE
Lists aren't displaying metadata correctly

### ISSUE THREAD

**Issue by chiefkes** [drinfernoo/repository.openmeta#1]
I've been testing out skyfsza/serpentdrago's Auramod skin and i've noticed that metadata doesn't seem to be conveyed correctly into widgets when using openmeta lists as a source. Compare for example a widget pulling from Seren or Gaia with one pulling from openmeta and you'll see what I'm saying. 

I have also found that metadata seems to be missing and inconsistent when directly browsing the different lists in openmeta using a feature rich view type like Showcase in Aura/Auramod. I wonder if these issues are related. To give some examples:

- Top 250 IMDB seems mostly complete, but clearlogos don't display
- Latest releases (trakt): lots of metadata missing, but clearlogos do display

**Comment by pencey** [comment]
Hello @chiefkes, I was wondering about Auramod. I currently use Aura and looked everywhere for the differences/additions, or a screenshot but couldn't find anything. I found the skin in is GitHub but there's not much in the way of a diff between JM's Aura. Could you provide screenshots to imgur and/or what additions make it better? Thank you!

**Comment by chiefkes** [comment]
I'd recommend installing it and checking it out, it's basically a netflix mod and looks bloody fantastic and runs a hell of a lot better than Titan Bingie Mod being that it's based on Aura

**Comment by drinfernoo** [comment]
This is a skin issue, I believe. @skyfsza, any input?

**Comment by skyfsza** [comment]
I would need more details on what metadata is missing. The skin simply displays content set in Kodi Infolabels, if it displays with one add-on but not another, I would imagine the addon is not correctly filling the infolabels.

**Comment by drinfernoo** [comment]
Could you please reopen this issue on the appropriate GitHub repository for either [OpenMeta](https://www.github.com/drinfernoo/plugin.video.openmeta/) or [OpenInfo](https://www.github.com/drinfernoo/script.extendedinfo/)?
