### ISSUE TITLE
Bring back set default player option

### ISSUE THREAD

**Issue by chiefkes** [drinfernoo/repository.openmeta#3]
I can see that you've obviously gone to lengths to seriously streamline openmeta and it's working brilliantly. Would you consider adding back the option to set the default player from a context menu? Currently everything defaults to loading up the player selection window. Would also be nice to have the option to enable and disable players from the settings menu

**Comment by akuiraz86** [comment]
i would also like to see the default player setting...

**Comment by drinfernoo** [comment]
This is a feature we've been looking into 👍

**Comment by drinfernoo** [comment]
Could you please reopen this issue on the appropriate GitHub repository for [OpenMeta](https://www.github.com/drinfernoo/plugin.video.openmeta/)?
