### ISSUE TITLE
Changing Genre of a movie not swapping

### ISSUE THREAD

**Issue by lukehansford** [drinfernoo/repository.openmeta#9]
When you change genres under movie search they do not update the list of movies.

**Comment by drinfernoo** [comment]
What do you mean by this? Can you show screenshots or an example of some kind?

**Comment by drinfernoo** [comment]
Also, which add-on are you referring to? Could you please reopen this issue on the appropriate GitHub repository for either [OpenMeta](https://www.github.com/drinfernoo/plugin.video.openmeta/) or [OpenInfo](https://www.github.com/drinfernoo/script.extendedinfo/)?
